### model
model_name_or_path: alignment-handbook/zephyr-7b-sft-full
adapter_name_or_path: outputs/llm_bench/iteration_stage_1/policy_dpo/zephyr-7b-sft-full/lora/checkpoint-2500

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: ultrafeedback_iter2_pair
template: zephyr
cutoff_len: 1024
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/llm_bench/iteration_stage_2/policy_dpo/zephyr-7b-sft-full-v2/lora/
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 4.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200
